CREATE DATABASE e_book_e_commerce 
CREATE TABLE IF NOT EXISTS users(
    ID INT NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    Lastname VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT ON UPDATE,
    Deted VARCHAR(10),
    PRIMARY KEY(ID)
); 
CREATE TABLE IF NOT EXISTS categories(
    ID INT NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT ON UPDATE
); 
CREATE TABLE IF NOT EXISTS products(
    ID INT NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    Pages VARCHAR(255),
    categoryID INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT ON UPDATE,
    PRIMARY KEY(ID),
    FOREIGN KEY(categoryID) REFERENCES categories(ID)
); 
CREATE TABLE IF NOT EXISTS imagesProducts(
    ID INT NOT NULL UNIQUE,
    Src VARCHAR(255) NOT NULL,
    ProductID INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT ON UPDATE,
    PRIMARY KEY(ID),
    FOREIGN KEY(ProductID) REFERENCES products(ID)
); 
CREATE TABLE IF NOT EXISTS orders(
    ID INT NOT NULL UNIQUE,
    Descripcion VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT ON UPDATE,
    PRIMARY KEY(ID)
); 
CREATE TABLE IF NOT EXISTS lineOrders(
    ID INT NOT NULL UNIQUE,
    OrderID VARCHAR(255) NOT NULL,
    ProductID VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT ON UPDATE,
    PRIMARY KEY(ID),
    FOREIGN KEY(OrderID) REFERENCES orders(ID),
    FOREIGN KEY(ProductID) REFERENCES products(ID)
);